before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: wx0dacFEPdgNkU6bgc36h/u2i01bCTGwTHjd+gnssMiDDfq0Pb36KgaG+9Use1vWoDGzdqYZ+eLDGvOrkdZ50/VMv7tF9Y4927R3gp5452nSbobQdomW0DSKGv49key1Hm0QyOLavnmXnom9inFm0Vp+me+U29DZs3TakppsE41K4ECzvAAy06Ne7TIUEFHCzpj/M8orsk0N/bz7tBeiCRcBiAq2s/W6bt+WSOebZBgAPLh34NWJ/I3orNKxiHSNmt3yLBmhPysFF+WNXe2rg5aHJeCrYZDggknK2HoPNVp3u/26r5GSskkkQxa4QvAMAgZCL+85pN/zGavoptSOeLbdqkieGUUCIKC6LSLnuWQ7Uji491Ik1XizETNTa2w+5vBoU1GK+QmVfT7TAOqeXy64zE+pa32rWQdZCZ29uvF2cZ1HCu9ybTx9Cz/5NmesE2Xct/tMtqo6AIhL9JwY9Cu7ZK1e67iAuvLlUBxYXR7WLqfUN1JFGhXgc0WknqSIoscjKGu1Cm+x4VdYZwpjuKUp2xnGlOMZ5U1ZJZxkYjOQi8Eb9vhCGOU7oNXhwghRYYEzqQde8KwXwHSbzDsllw0MoPdjgt8zXJHbu4wANPmIerYQRNzoN3bCCeiWHrrnfZyJDodHvx++eKbyyeHqBnKwCN8WgBp59LLhbYZIUVQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
